name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm install
          
      - name: Build project for Windows and Linux
        run: |
          npm run build:electron:windows
          npm run build:electron:linux
        
      - name: Upload built files
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Built files
          path: dist/
          if-no-files-found: error
  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm install
          
      - name: Build project for Mac
        run: npm run build:electron:mac
        
      - name: Upload built files
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Built files for Mac
          path: dist/
          if-no-files-found: error
